version: "3.7"
services:
  # app1
  app1:
#    expose:
#      - "11211"
    container_name: app1
    build:
      context: ./app1
      dockerfile: app1.Dockerfile
    depends_on:
      - memcached
    networks:
      - memcached

  # app2
  app2:
    container_name: app2
    build:
      context: ./app2
      dockerfile: app2.Dockerfile
    depends_on:
      - memcached
    networks:
      - memcached

  # memcached
  memcached:
    container_name: memcached
    image: memcached:latest
    expose:
      - "11211"
    restart: always
    networks:
      - memcached

networks:
  memcached: